// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqQKmAUH40Z4c-5O0bE1CzXuWjqdIdThM',
    appId: '1:109684335426:web:73cb405d6c41f8b6a51edb',
    messagingSenderId: '109684335426',
    projectId: 'scc-app-89ec4',
    authDomain: 'scc-app-89ec4.firebaseapp.com',
    storageBucket: 'scc-app-89ec4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJc4TrTV_v64nUDwA1Ln8q7lM2vxohA6c',
    appId: '1:109684335426:android:0bd593f615d2ea58a51edb',
    messagingSenderId: '109684335426',
    projectId: 'scc-app-89ec4',
    storageBucket: 'scc-app-89ec4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSQ84nGKwYCHPjPEB0wq6eTfBIHfBE3iY',
    appId: '1:109684335426:ios:f203fee5e9d82547a51edb',
    messagingSenderId: '109684335426',
    projectId: 'scc-app-89ec4',
    storageBucket: 'scc-app-89ec4.firebasestorage.app',
    iosBundleId: 'com.uniss.scc',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSQ84nGKwYCHPjPEB0wq6eTfBIHfBE3iY',
    appId: '1:109684335426:ios:b37ae537452570b3a51edb',
    messagingSenderId: '109684335426',
    projectId: 'scc-app-89ec4',
    storageBucket: 'scc-app-89ec4.firebasestorage.app',
    iosBundleId: 'com.example.sccApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqQKmAUH40Z4c-5O0bE1CzXuWjqdIdThM',
    appId: '1:109684335426:web:af466e1f1e311912a51edb',
    messagingSenderId: '109684335426',
    projectId: 'scc-app-89ec4',
    authDomain: 'scc-app-89ec4.firebaseapp.com',
    storageBucket: 'scc-app-89ec4.firebasestorage.app',
  );
}
